sqlserver_factory: # Profile name - must match the profile: value in dbt_project.yml
  target: dev # Default environment (Target) name - must match the target: value in dbt_project.yml if there is one
  outputs:
    dev: # the targeted environment name
      type: sqlserver # Database type - must match the type: value in dbt_project.yml if there is one
      driver: 'ODBC Driver 17 for SQL Server' # SQL Server driver name - must match the ODBC driver name (driver: may be defined in dbt_project.yml as well, but redundant)
      server: [SERVERNAME\DBSERVERNAME] #odb # Replace with your SQL Server instance name or IP
      port: 1433                # Default SQL Server port (Set in server Connection details) - change if using a different port
      database: [DATABASENAME] # Insert your database name
      schema: dbo              # dbo or Production1. Insert your schema name, that was pre-created in your database (SQL: CREATE SCHEMA ...)
      windows_login: true       # Set to true if using Windows Authentication, false if using SQL Server Authentication. Check MS SQL server authentication settings first!
      user: [USERNAME]          # Insert your Windows Authentication / SQL Server username
      password: [PASSWORD]      # Insert your Windows Authentication / SQL Server password
      encrypt: false            # Do not use if possible! Disable SSL encryption (to avoid possible connection issues due to inappropriate certificate)
      
    dev2: # another environment, could be targeted by 'dbt run --target dev2' command
      database: FacilityManagement_Core
      driver: 'ODBC Driver 17 for SQL Server'
      server: [SERVERNAME\DBSERVERNAME] #same as above
      port: 1433
      threads: 1 # Number of threads to use for multi-threaded execution, for performance optimization, in case of large datasets 
      type: sqlserver
      user: [OTHER USERNAME]    # to test other user rights, User must be added in SQL Server
      password: [OTHER USER'S PASSWORD]