version: 2 # Version of the dbt project configuration file, default is 2, declared by dbt

models:
  - name: stg_production        # Name of the model you want to test
    schema: dbo   # Specify the schema where the view will be created
    +staging: true # declare the model as a staging model
    +stage: true # Must be set to true for staging models
    description: "Staging table for production data"
    columns:
      - name: ProcessTemp    # Column to test
        data-tests: #name: 'data-tests' since dbt v1.8!
          - check_value_range
          # use other test sql model, with parameters
          #- check_value_range_pars:   # Reference to your specific test
          #  min: 273.15           # Minimum value in Kelvin
          #  max: 313.7           # Maximum value in Kelvin
          #- test_positive_values # Reference to your generic test
          #- not_null            # Reference to your specific test

  # You can also create a more detailed test configuration  
  #- name: fct_sales
  #  columns:
  #    - name: ProcessTemp
  #      tests:
  #        - positive_values:
  #            severity: error    # Can be error or warn
  #            where: "transaction_date > '2024-01-01'"  # Optional filter
  #            config:
  #              store_failures: true   # Store failed records in a table
  #              schema: dbt_test_results  # Schema for storing results